<Error>
<Message>An error has occurred.</Message>
<ExceptionMessage>Exception of type 'System.OutOfMemoryException' was thrown.</ExceptionMessage>
<ExceptionType>System.OutOfMemoryException</ExceptionType>
<StackTrace> at System.IO.MemoryStream.set_Capacity(Int32 value) at System.IO.MemoryStream.EnsureCapacity(Int32 value) at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count) at Ionic.Zip.CountingStream.Write(Byte[] buffer, Int32 offset, Int32 count) in C:\projects\dotnetzip-semverd\src\Zip.Shared\Shared.cs:line 798 at Ionic.Zip.CountingStream.Write(Byte[] buffer, Int32 offset, Int32 count) in C:\projects\dotnetzip-semverd\src\Zip.Shared\Shared.cs:line 798 at Ionic.Zlib.ParallelDeflateOutputStream.EmitPendingBuffers(Boolean doAll, Boolean mustWait) in C:\projects\dotnetzip-semverd\src\Zlib.Shared\ParallelDeflateOutputStream.cs:line 959 at Ionic.Zlib.ParallelDeflateOutputStream.Write(Byte[] buffer, Int32 offset, Int32 count) in C:\projects\dotnetzip-semverd\src\Zlib.Shared\ParallelDeflateOutputStream.cs:line 561 at Ionic.Crc.CrcCalculatorStream.Write(Byte[] buffer, Int32 offset, Int32 count) in C:\projects\dotnetzip-semverd\src\Zlib.Shared\CRC32.cs:line 710 at Ionic.Zip.ZipEntry._WriteEntryData(Stream s) in C:\projects\dotnetzip-semverd\src\Zip.Shared\ZipEntry.Write.cs:line 1460 at Ionic.Zip.ZipEntry.Write(Stream s) in C:\projects\dotnetzip-semverd\src\Zip.Shared\ZipEntry.Write.cs:line 2220 at Ionic.Zip.ZipFile.Save() in C:\projects\dotnetzip-semverd\src\Zip.Shared\ZipFile.Save.cs:line 168 at Ionic.Zip.ZipFile.Save(Stream outputStream) in C:\projects\dotnetzip-semverd\src\Zip.Shared\ZipFile.Save.cs:line 571 at Calpine.ErcotInterface.WebApi.DownloadReports.DownloadReportsWebApiBoundary.GetFileContentResult(String reportId, IEnumerable`1 reports, String errorMessage) in D:\a\1\s\Calpine.ErcotInterface.WebApi\DownloadReports\DownloadReportsWebApiBoundary.cs:line 72 at Calpine.ErcotInterface.WebApi.DownloadReports.DownloadReportsWebApiBoundary.Success(DownloadReportsResponse response) in D:\a\1\s\Calpine.ErcotInterface.WebApi\DownloadReports\DownloadReportsWebApiBoundary.cs:line 46 at Calpine.ErcotInterface.Core.UseCases.DownloadReports.DownloadReportsInteractor`1.<HandleAsync>d__4.MoveNext() in D:\a\1\s\Calpine.ErcotInterface.Core\UseCases\DownloadReports\DownloadReportsInteractor.cs:line 57 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Calpine.ErcotInterface.WebApi.DownloadReports.ReportsController.<Get>d__3.MoveNext() in D:\a\1\s\Calpine.ErcotInterface.WebApi\DownloadReports\ReportsController.cs:line 54 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()</StackTrace>
</Error>